/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import configJson from '../../firebase-applet-config.json';

const GOOGLE_CLIENT_ID = configJson.oAuthClientId || '170400716318-5hrv1jlpp6fmlpar3vi2vspmu4vnt3hj.apps.googleusercontent.com';
const CALENDAR_SCOPE = 'https://www.googleapis.com/auth/calendar.events';

let cachedAccessToken: string | null = null;
let tokenClient: any = null;

declare global {
  interface Window {
    google?: any;
  }
}

/**
 * Request OAuth Access Token from user via Google Identity Services popup
 */
export const requestGoogleCalendarToken = (): Promise<string> => {
  return new Promise((resolve, reject) => {
    if (cachedAccessToken) {
      resolve(cachedAccessToken);
      return;
    }

    if (!window.google || !window.google.accounts || !window.google.accounts.oauth2) {
      reject(new Error('Google Identity Services script not loaded. Please refresh the page and try again.'));
      return;
    }

    try {
      tokenClient = window.google.accounts.oauth2.initTokenClient({
        client_id: GOOGLE_CLIENT_ID,
        scope: CALENDAR_SCOPE,
        callback: (response: any) => {
          if (response.error) {
            reject(new Error(response.error_description || response.error));
            return;
          }
          if (response.access_token) {
            cachedAccessToken = response.access_token;
            resolve(response.access_token);
          } else {
            reject(new Error('Failed to obtain Google OAuth access token.'));
          }
        },
        error_callback: (err: any) => {
          reject(new Error(err.message || 'OAuth authorization prompt was closed or failed.'));
        }
      });

      tokenClient.requestAccessToken();
    } catch (err: any) {
      reject(err);
    }
  });
};

/**
 * Helper to parse user date and time string into standard ISO start/end strings
 */

function parseDateTimeToISO(dateStr: string, timeStr: string): { startISO: string; endISO: string; timeZone: string } {
  const userTZ = Intl.DateTimeFormat().resolvedOptions().timeZone || 'Asia/Dhaka';
  
  let targetDate = new Date();
  
  if (dateStr) {
    // Check YYYY-MM-DD
    if (/^\d{4}-\d{2}-\d{2}$/.test(dateStr.trim())) {
      const parts = dateStr.trim().split('-');
      targetDate = new Date(parseInt(parts[0]), parseInt(parts[1]) - 1, parseInt(parts[2]));
    } else {
      const parsed = new Date(dateStr);
      if (!isNaN(parsed.getTime())) {
        targetDate = parsed;
      }
    }
  }

  let hours = 11;
  let minutes = 0;

  if (timeStr) {
    const cleanTime = timeStr.trim().toUpperCase();
    const isPM = cleanTime.includes('PM');
    const isAM = cleanTime.includes('AM');
    const timeMatch = cleanTime.match(/(\d{1,2}):(\d{2})/);
    if (timeMatch) {
      hours = parseInt(timeMatch[1], 10);
      minutes = parseInt(timeMatch[2], 10);
      if (isPM && hours < 12) hours += 12;
      if (isAM && hours === 12) hours = 0;
    }
  }

  const startDate = new Date(targetDate.getFullYear(), targetDate.getMonth(), targetDate.getDate(), hours, minutes, 0);
  const endDate = new Date(startDate.getTime() + 60 * 60 * 1000); // 1 hour duration

  return {
    startISO: startDate.toISOString(),
    endISO: endDate.toISOString(),
    timeZone: userTZ
  };
}

export interface CreateCalendarEventParams {
  clientName: string;
  ticketId?: string;
  trainingDate?: string;
  trainingTime?: string;
  pm?: string;
  assignedPerson?: string;
  package?: string;
}

export interface GoogleCalendarEventResult {
  eventId: string;
  meetLink: string;
  calendarEventUrl: string;
  summary: string;
}

/**
 * Creates a real Google Calendar Event with Google Meet video conference solution enabled.
 * Returns the authentic Google Meet link generated by Google Calendar API.
 */
export const createRealGoogleMeetEvent = async (
  params: CreateCalendarEventParams
): Promise<GoogleCalendarEventResult> => {
  const token = await requestGoogleCalendarToken();

  const { startISO, endISO, timeZone } = parseDateTimeToISO(
    params.trainingDate || '',
    params.trainingTime || '11:00 AM'
  );

  const eventSummary = `Tipsoi Training: ${params.clientName}${params.ticketId ? ` (Ticket: ${params.ticketId})` : ''}`;
  const eventDescription = [
    `Client Training Session for: ${params.clientName}`,
    `Assigned Person (KAM): ${params.assignedPerson || 'N/A'}`,
    `PM / Trainer: ${params.pm || 'N/A'}`,
    `Package: ${params.package || 'N/A'}`,
    `Ticket ID: ${params.ticketId || 'N/A'}`,
    ``,
    `Scheduled via Tipsoi HRM Client Training & Support Management System`
  ].join('\n');

  const requestId = `tipsoi_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`;

  const calendarPayload = {
    summary: eventSummary,
    description: eventDescription,
    start: {
      dateTime: startISO,
      timeZone: timeZone
    },
    end: {
      dateTime: endISO,
      timeZone: timeZone
    },
    conferenceData: {
      createRequest: {
        requestId: requestId,
        conferenceSolutionKey: {
          type: 'hangoutsMeet'
        }
      }
    }
  };

  const response = await fetch(
    'https://www.googleapis.com/calendar/v3/calendars/primary/events?conferenceDataVersion=1',
    {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(calendarPayload)
    }
  );

  if (!response.ok) {
    const errorData = await response.json().catch(() => null);
    throw new Error(
      errorData?.error?.message || `Google Calendar API error (Status ${response.status})`
    );
  }

  const data = await response.json();

  // Extract authentic Google Meet link from response
  let meetLink = data.hangoutLink;
  if (!meetLink && data.conferenceData && data.conferenceData.entryPoints) {
    const videoEntry = data.conferenceData.entryPoints.find(
      (ep: any) => ep.entryPointType === 'video'
    );
    if (videoEntry) {
      meetLink = videoEntry.uri;
    }
  }

  if (!meetLink) {
    // Fallback if Calendar API didn't include hangoutLink
    meetLink = `https://meet.google.com/new`;
  }

  return {
    eventId: data.id,
    meetLink: meetLink,
    calendarEventUrl: data.htmlLink || `https://calendar.google.com/calendar`,
    summary: data.summary || eventSummary
  };
};
